unit uTxt2xlsx_xml;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms, StrUtils_d7,
  ads_strg, uLogRead, ComCtrls, dialogs,  ads_date, Strutils, StdCtrls, System.ZLib ;

type
  TTxt2xlsx_xml = class(Tobject)
  private
    _iNrcol,
    _iNrrow   : integer;
    filter    : boolean;
    InFile    : Ansistring;
    OutFile   : Ansistring;
    _aslogfile    : Ansistring;
    slXml     : Tstringlist;
    procedure createxml;
    procedure createfixedstyle;
  public
    constructor create(asInFile : ansistring; asOutFile : Ansistring; aslogfile : ansistring); overload;
	  destructor destroy; override;
  end;

var
  Txt2xlsx_xml : TTxt2xlsx_xml;

implementation

(*
  !!
  TXLSXxml - is declared in ulogread
*)
constructor TTxt2xlsx_xml.create(asInFile : ansistring; asOutFile : Ansistring;
                                 aslogfile : ansistring);
begin
  inherited Create;             // Call TObject.Create.
  _aslogfile := aslogfile;
  InFile    := asInFile;
  OutFile   := asOutFile;

  //Check that the arcol has values.
  //only continue if it does otherwise exit.
  slXml  := Tstringlist.Create;

  Createfixedstyle;
  createxml;

end;
//-------------------------------------------------------------------------------------------------------------------
destructor TTxt2xlsx_xml.destroy;
begin
  //make sure what was created is destroyed.
  FreeAndnil(slXml);
  inherited Destroy;
end;
//-------------------------------------------------------------------------------------------------------------------
procedure TTxt2xlsx_xml.createxml;
var
  irow     : integer;
  icnt     : integer;
  rc1Flogs : TLoginfo;
  sfile, sfolder, sfilefol : ansistring;
  asType, asstyle, asdt, asnewname, asext   : ansistring;
  dtDt : TDatetime;
  LInput, LOutput: TFileStream;
  LZip: TZCompressionStream;
begin

  //determine the nr of columns that will be needed.

 // Read summary
 // Add the "header details"
  slXml.add('<Worksheet ss:Name="Read Summary">');
  slXml.add('<x:WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">');
  slXml.add('<Print>');
  slXml.add('<ValidPrinterInfo/>');
  slXml.add('<PaperSizeIndex>1</PaperSizeIndex>');
  slXml.add('<Scale>100</Scale>');
  slXml.add('<FitWidth>1</FitWidth>');
  slXml.add('<FitHeight>1</FitHeight>');
  slXml.add('<HorizontalResolution>300</HorizontalResolution>');
  slXml.add('<VerticalResolution>300</VerticalResolution>');
  slXml.add('</Print>');
  slXml.add('<Zoom>100</Zoom>');
  slXml.add('<x:PageSetup>');
  slXml.add('<x:Header />');
  slXml.add('<PageMargins x:Left="0.08" x:Right="0.08"/>');
  slXml.add('</x:PageSetup>');
  slXml.add('<Selected/>');
  slXml.add('<FreezePanes/>');
  slXml.add('<FrozenNoSplit/>');
  slXml.add('<SplitHorizontal>1</SplitHorizontal>');
  slXml.add('<TopRowBottomPane>2</TopRowBottomPane>');
  slXml.add('<ActivePane>2</ActivePane>');
  slXml.add('<Panes>');
  slXml.add('<Pane>');
  slXml.add('<Number>2</Number>');
  slXml.add('</Pane>');
  slXml.add('<Pane>');
  slXml.add('<Number>2</Number>');
  slXml.add('</Pane>');
  slXml.add('</Panes>');
  slXml.add('<ProtectObjects>False</ProtectObjects>');
  slXml.add('<ProtectScenarios>False</ProtectScenarios>');
  slXml.add('</x:WorksheetOptions>');

  assignfile(ffollogs, _aslogfile);
  reset(ffollogs);
  if filesize(ffollogs) > 0 then begin

    //Need to adjust the range
    slXml.Add('<AutoFilter x:Range="R4C1:R124C4" xmlns="urn:schemas-microsoft-com:office:excel"></AutoFilter><Table ss:StyleID="_body">');
    slXml.add('<ss:Column ss:AutoFitWidth="1" ss:Width="300"/>');
    slXml.add('<ss:Column ss:AutoFitWidth="1" ss:Width="90"/>');
    slXml.add('<ss:Column ss:AutoFitWidth="1" ss:Width="105"/>');
    slXml.add('<ss:Column ss:AutoFitWidth="1" ss:Width="450"/>');
    slXml.add('<Row ss:Height="16" ss:StyleID="_body"><Cell ss:StyleID="systemtitle__l" ss:MergeAcross="3"><Data ss:Type="String">Log Read results</Data></Cell></Row> ');
    //Add the file location
    slXml.add('<Row ss:Height="16" ss:StyleID="_body"><Cell ss:StyleID="systemtitle2__l" ss:MergeAcross="3"><Data ss:Type="String">Output Location: '+ OutFile +'</Data></Cell></Row> ');
    slXml.add('<Row ss:AutoFitHeight="0" ss:StyleID="_body" ss:Height="14">');
    slXml.add('<Cell ss:StyleID="parskip"/> ');
    slXml.add('</Row> ');
    //Add the top Row - aka the headings
    slXml.Add('<Row ss:AutoFitHeight="1" ss:Height="28">');
    slXml.Add('<Cell ss:StyleID="header__c" ss:Index="1"><Data ss:Type="String">Filename</Data></Cell>');
    slXml.Add('<Cell ss:StyleID="header__c" ss:Index="2"><Data ss:Type="String">Linenr</Data></Cell>');
    slXml.Add('<Cell ss:StyleID="header__c" ss:Index="3"><Data ss:Type="String">Types</Data></Cell>');
    slXml.Add('<Cell ss:StyleID="header__c" ss:Index="4"><Data ss:Type="String">Issues Found</Data></Cell>');
    slXml.Add('</Row>');

    try
      read(ffollogs, rc1Flogs);
      while not EOF(ffollogs) do begin
        read(ffollogs, rc1Flogs);

        if sfolder <> rc1flogs.folder then sfilefol := rc1flogs.Folder ;
        if sfile <> rc1flogs.filename then sfilefol := rc1flogs.Folder+' - File name : ' + rc1flogs.Filename;

        if (lower(rc1flogs.types) <> 'last') or (lower(rc1flogs.types) <> 'nobosdata')          then begin
          slXml.Add('<Row ss:AutoFitHeight="1" ss:Height="15">');

          if rc1flogs.types = 'Merge'              then begin astype := 'Merge Notes';         asstyle := 'data__l_1'; end
          else if rc1flogs.types = 'Conversion'    then begin astype := 'Conversion Notes';    asstyle := 'data__l_1'; end
          else if rc1flogs.types = 'Division'      then begin astype := 'Division by Zero';    asstyle := 'data__l1'; end
          else if rc1flogs.types = 'Uninitialized' then begin astype := 'Uninitialized Notes'; asstyle := 'data__l_1'; end
          else if rc1flogs.types = 'AllOth'        then begin astype := 'All Other Notes';     asstyle := 'data__l_1'; end
          else if rc1flogs.types = 'Invalid'       then begin astype := 'Invalid Notes';       asstyle := 'data__l_1'; end
          else if rc1flogs.types = 'Cust'          then begin astype := 'Custom Notes';        asstyle := 'data__l_1'; end
          else if rc1flogs.types = 'missval'       then begin astype := 'Missing Val Gen.';    asstyle := 'data__l_1'; end
          else if rc1flogs.types = 'repbyval'      then begin astype := 'Repeats of by';       asstyle := 'data__l_1'; end
          else if rc1flogs.types = 'methop'        then begin astype := 'Math. Operations';    asstyle := 'data__l_1'; end
          else if rc1flogs.types = 'indataempt'    then begin astype := 'Empty Input Data';    asstyle := 'data__l_1'; end
          else if rc1flogs.types = 'nobystate'     then begin astype := 'No by Statement';     asstyle := 'data__l_1'; end
          else if rc1flogs.types = 'NOTE'          then begin astype := 'Notes';               asstyle := 'data__l_1'; end
          else if rc1flogs.types = 'Info'          then begin astype := 'Info';                asstyle := 'data__l_1'; end
          else if rc1flogs.types = 'Error'         then begin astype := 'Error';               asstyle := 'data__l_3'; end
          else if rc1flogs.types = 'Warning'       then begin astype := 'Warning';             asstyle := 'data__l1'; end;

          slXml.Add('<Cell ss:StyleID="'+ asstyle+'" ss:Index="1"><Data ss:Type="String">'+sfilefol+'</Data></Cell> ');
          slXml.Add('<Cell ss:StyleID="'+ asstyle+'" ss:Index="2"><Data ss:Type="String">'+inttostr(rc1flogs.LineNr)+'</Data></Cell> ');
          slXml.Add('<Cell ss:StyleID="'+ asstyle+'" ss:Index="3"><Data ss:Type="String">'+ astype +'</Data></Cell> ');
          slXml.Add('<Cell ss:StyleID="'+ asstyle+'" ss:Index="4"><Data ss:Type="String">'+ rc1flogs.entry+'</Data></Cell>');

          slXml.Add('</Row>');
        end;
        sfile   := rc1flogs.Filename;
        sfolder := rc1flogs.Folder;

        inc(icnt);

        (*if icnt mod 1000 = 0 then  begin
          fmProgress.SetPogress(icnt);
          application.ProcessMessages;
        end; *)
    end;

    finally
       closefile(ffollogs);
//       fmProgress.Hide;
    end;
  end;

  slXml.Add('</Table>');
  slXml.Add('</Worksheet>');
  slXml.Add('</Workbook>');

  //Check of the output file exists. If it does. Zip the old one name it to be equal to the timestamp of the files
  //as suffix and save the new one.
  if FileExists(Outfile) then begin
    dtdt      := File_GetLastModifiedDate(Outfile);
    asdt      := Replacestr(DateTimeToStr(dtDt),'/','_');
    asdt      := Replacestr(asdt, ':','_');
    asext     := ExtractFileExt(outfile);
    asnewname := Extractfilename(outfile);
    asnewname := replacestr(asnewname, asext, '');
    asnewname := IncludeTrailingPathDelimiter(ExcludeTrailingPathDelimiter(ExtractFilePath(outfile)))+ ExtractfileName(asnewname)+'_'+asdt+'.'+asext;

    if RenameFile(outfile, asNewname) then begin
       //Left open on purpose for the time being
      { Create the Input, Output, and Compressed streams. }
      LInput := TFileStream.Create(asnewname, fmOpenRead);
      LOutput := TFileStream.Create(asnewname + '.zip', fmCreate);
      LZip := TZCompressionStream.Create(LOutput);

      { Compress data. }
      LZip.CopyFrom(LInput, LInput.Size);

      { Free the streams. }
      LZip.Free;
      LInput.Free;
      LOutput.Free;
    end;
    slXml.SaveToFile(OutFile);
  end else begin
    slXml.SaveToFile(OutFile);
  end;

end;
//-------------------------------------------------------------------------------------------------------------------
procedure TTxt2xlsx_xml.Createfixedstyle;
var
  dtnow  : TDatetime;
  asUser : ansistring;
begin
  dtnow := now();
  asUser              := GetEnvironmentVariable('USERNAME');

  //Set the default initial style. This might get update but for now this is fine
  slXml.Add('<?xml version="1.0" encoding="windows-1252"?>');
  slXml.Add('<?mso-application progid="Excel.Sheet"?>');
  slXml.Add('<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"');
  slXml.Add('          xmlns:x="urn:schemas-microsoft-com:office:excel"');
  slXml.Add('          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"');
  slXml.Add('          xmlns:html="http://www.w3.org/TR/REC-html40">');
  slXml.Add('<DocumentProperties xmlns="urn:schemas-microsoft-com:office">');
  slXml.Add('<Author>'+asUser+'  </Author>');
  slXml.Add('<LastAuthor> '+asUser+'</LastAuthor>');
  slXml.Add('<Created> '+Datetimetostr(dtnow)+' </Created>');
  slXml.Add('<LastSaved> '+Datetimetostr(dtnow)+' </LastSaved>');
  slXml.Add('<Company>LogXpress</Company>');
  slXml.Add('<Version>XE10</Version>');
  slXml.Add('</DocumentProperties>');
  slXml.Add('<Styles>');
  slXml.Add('<Style ss:ID="_body">');
  slXml.Add(' <Interior ss:Pattern="Solid" />');
  slXml.Add(' <Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="_contents">');
  slXml.Add(' <Interior ss:Pattern="Solid" />');
  slXml.Add(' <Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="_pages">');
  slXml.Add(' <Interior ss:Pattern="Solid" />');
  slXml.Add(' <Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Left" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Top" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="table__l" ss:Parent="table"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="table__r" ss:Parent="table"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="table__c" ss:Parent="table"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="aftercaption">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="batch">');
  slXml.Add('<Font ss:FontName="Courier New, Courier, monospace" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="beforecaption">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="bodydate">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Vertical="Top" ss:Horizontal="Right"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="bycontentfolder">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="byline">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="byline__l" ss:Parent="byline"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="byline__r" ss:Parent="byline"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="byline__c" ss:Parent="byline"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="bylinecontainer">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="caption">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="caption__l" ss:Parent="caption"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="caption__r" ss:Parent="caption"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="caption__c" ss:Parent="caption"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="cell">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="container">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="contentfolder">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="contentitem">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="contentproclabel">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="contentprocname">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="contents">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="contentsdate">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="contenttitle" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Italic="1" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="continued">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" />');
  slXml.Add('<Interior ss:Color="#FFFFFF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__l" ss:Parent="data"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__r" ss:Parent="data"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__c" ss:Parent="data"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="dataemphasis" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Italic="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#FFFFFF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="dataemphasis__l" ss:Parent="dataemphasis"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="dataemphasis__r" ss:Parent="dataemphasis"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="dataemphasis__c" ss:Parent="dataemphasis"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="dataemphasisfixed" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Courier New, Courier, monospace" ss:Size="10" ss:Italic="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#FFFFFF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="dataemphasisfixed__l" ss:Parent="dataemphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="dataemphasisfixed__r" ss:Parent="dataemphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="dataemphasisfixed__c" ss:Parent="dataemphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="dataempty" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" />');
  slXml.Add('<Interior ss:Color="#FFFFFF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="dataempty__l" ss:Parent="dataempty"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="dataempty__r" ss:Parent="dataempty"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="dataempty__c" ss:Parent="dataempty"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datafixed" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Courier New, Courier" ss:Size="10" />');
  slXml.Add('<Interior ss:Color="#FFFFFF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datafixed__l" ss:Parent="datafixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datafixed__r" ss:Parent="datafixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datafixed__c" ss:Parent="datafixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datastrong" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#FFFFFF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datastrong__l" ss:Parent="datastrong"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datastrong__r" ss:Parent="datastrong"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datastrong__c" ss:Parent="datastrong"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datastrongfixed" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Courier New, Courier, monospace" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#FFFFFF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datastrongfixed__l" ss:Parent="datastrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datastrongfixed__r" ss:Parent="datastrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datastrongfixed__c" ss:Parent="datastrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="date">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="document">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="errorbanner">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="errorcontent">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="errorcontentfixed">');
  slXml.Add('<Font ss:FontName="Courier New, Courier" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="extendedpage">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Left" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Right" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Top" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Italic="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="fatalbanner">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="fatalbanner__l" ss:Parent="fatalbanner"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="fatalbanner__r" ss:Parent="fatalbanner"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="fatalbanner__c" ss:Parent="fatalbanner"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="fatalcontent">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="fatalcontent__l" ss:Parent="fatalcontent"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="fatalcontent__r" ss:Parent="fatalcontent"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="fatalcontent__c" ss:Parent="fatalcontent"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="fatalcontentfixed">');
  slXml.Add('<Font ss:FontName="Courier New, Courier" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="fatalcontentfixed__l" ss:Parent="fatalcontentfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="fatalcontentfixed__r" ss:Parent="fatalcontentfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="fatalcontentfixed__c" ss:Parent="fatalcontentfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="folderaction">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footer" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footer__l" ss:Parent="footer"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footer__r" ss:Parent="footer"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footer__c" ss:Parent="footer"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footeremphasis" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Italic="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footeremphasis__l" ss:Parent="footeremphasis"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footeremphasis__r" ss:Parent="footeremphasis"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footeremphasis__c" ss:Parent="footeremphasis"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footeremphasisfixed" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Courier New, Courier, monospace" ss:Size="10" ss:Italic="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footeremphasisfixed__l" ss:Parent="footeremphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footeremphasisfixed__r" ss:Parent="footeremphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footeremphasisfixed__c" ss:Parent="footeremphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerempty" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerempty__l" ss:Parent="footerempty"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerempty__r" ss:Parent="footerempty"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerempty__c" ss:Parent="footerempty"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerfixed" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Courier New, Courier" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerfixed__l" ss:Parent="footerfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerfixed__r" ss:Parent="footerfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerfixed__c" ss:Parent="footerfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerstrong" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerstrong__l" ss:Parent="footerstrong"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerstrong__r" ss:Parent="footerstrong"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerstrong__c" ss:Parent="footerstrong"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerstrongfixed" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Courier New, Courier, monospace" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerstrongfixed__l" ss:Parent="footerstrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerstrongfixed__r" ss:Parent="footerstrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="footerstrongfixed__c" ss:Parent="footerstrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="frame">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="graph">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Left" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Top" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="header" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" />');
  slXml.Add('<Interior ss:Color="#F5F7F1" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="header__l" ss:Parent="header"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="header__r" ss:Parent="header"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="header__c" ss:Parent="header"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headeremphasis" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Italic="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headeremphasis__l" ss:Parent="headeremphasis"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headeremphasis__r" ss:Parent="headeremphasis"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headeremphasis__c" ss:Parent="headeremphasis"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headeremphasisfixed" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Courier New, Courier, monospace" ss:Size="10" ss:Italic="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headeremphasisfixed__l" ss:Parent="headeremphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headeremphasisfixed__r" ss:Parent="headeremphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headeremphasisfixed__c" ss:Parent="headeremphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerempty" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" />');
  slXml.Add('<Interior ss:Color="#F5F7F1" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerempty__l" ss:Parent="headerempty"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerempty__r" ss:Parent="headerempty"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerempty__c" ss:Parent="headerempty"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerfixed" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Courier New, Courier" ss:Size="10" />');
  slXml.Add('<Interior ss:Color="#F5F7F1" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerfixed__l" ss:Parent="headerfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerfixed__r" ss:Parent="headerfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerfixed__c" ss:Parent="headerfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headersandfooters" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headersandfooters__l" ss:Parent="headersandfooters"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headersandfooters__r" ss:Parent="headersandfooters"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headersandfooters__c" ss:Parent="headersandfooters"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerstrong" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerstrong__l" ss:Parent="headerstrong"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerstrong__r" ss:Parent="headerstrong"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerstrong__c" ss:Parent="headerstrong"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerstrongfixed" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Courier New, Courier, monospace" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerstrongfixed__l" ss:Parent="headerstrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerstrongfixed__r" ss:Parent="headerstrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="headerstrongfixed__c" ss:Parent="headerstrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="index">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="indexaction">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="indexitem">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="indexprocname">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="indextitle" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Italic="1" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="layoutcontainer">');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="layoutregion">');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="list">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="list10">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="list2">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="list3">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="list4">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="list5">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="list6">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="list7">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="list8">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="list9">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="listitem">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="listitem10">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="listitem2">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="listitem3">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="listitem4">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="listitem5">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="listitem6">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="listitem7">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="listitem8">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="listitem9">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="note">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="note__l" ss:Parent="note"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="note__r" ss:Parent="note"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="note__c" ss:Parent="note"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="notebanner">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="notebanner__l" ss:Parent="notebanner"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="notebanner__r" ss:Parent="notebanner"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="notebanner__c" ss:Parent="notebanner"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="notecontent" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="notecontent__l" ss:Parent="notecontent"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="notecontent__r" ss:Parent="notecontent"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="notecontent__c" ss:Parent="notecontent"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="notecontentfixed">');
  slXml.Add('<Font ss:FontName="Courier New, Courier" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="notecontentfixed__l" ss:Parent="notecontentfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="notecontentfixed__r" ss:Parent="notecontentfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="notecontentfixed__c" ss:Parent="notecontentfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="output">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Left" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Top" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="pageno">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Vertical="Top" ss:Horizontal="Right"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="pages">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="pagesdate">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="pagesitem">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="pagesproclabel">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="pagesprocname">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="pagestitle" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Italic="1" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="paragraph">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="parskip" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="prepage">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="proctitle" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="proctitlefixed" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Courier New, Courier, monospace" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooter" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooter__l" ss:Parent="rowfooter"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooter__r" ss:Parent="rowfooter"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooter__c" ss:Parent="rowfooter"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooteremphasis" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Italic="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooteremphasis__l" ss:Parent="rowfooteremphasis"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooteremphasis__r" ss:Parent="rowfooteremphasis"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooteremphasis__c" ss:Parent="rowfooteremphasis"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooteremphasisfixed" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Courier New, Courier, monospace" ss:Size="10" ss:Italic="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooteremphasisfixed__l" ss:Parent="rowfooteremphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooteremphasisfixed__r" ss:Parent="rowfooteremphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooteremphasisfixed__c" ss:Parent="rowfooteremphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterempty" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterempty__l" ss:Parent="rowfooterempty"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterempty__r" ss:Parent="rowfooterempty"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterempty__c" ss:Parent="rowfooterempty"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterfixed" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Courier New, Courier" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterfixed__l" ss:Parent="rowfooterfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterfixed__r" ss:Parent="rowfooterfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterfixed__c" ss:Parent="rowfooterfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterstrong" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterstrong__l" ss:Parent="rowfooterstrong"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterstrong__r" ss:Parent="rowfooterstrong"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterstrong__c" ss:Parent="rowfooterstrong"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterstrongfixed" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Courier New, Courier, monospace" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterstrongfixed__l" ss:Parent="rowfooterstrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterstrongfixed__r" ss:Parent="rowfooterstrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowfooterstrongfixed__c" ss:Parent="rowfooterstrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheader" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" />');
  slXml.Add('<Interior ss:Color="#F5F7F1" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheader__l" ss:Parent="rowheader"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheader__r" ss:Parent="rowheader"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheader__c" ss:Parent="rowheader"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderemphasis" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Italic="1" />');
  slXml.Add('<Interior ss:Color="#F5F7F1" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderemphasis__l" ss:Parent="rowheaderemphasis"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderemphasis__r" ss:Parent="rowheaderemphasis"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderemphasis__c" ss:Parent="rowheaderemphasis"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderemphasisfixed" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Courier New, Courier, monospace" ss:Size="10" ss:Italic="1" />');
  slXml.Add('<Interior ss:Color="#F5F7F1" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderemphasisfixed__l" ss:Parent="rowheaderemphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderemphasisfixed__r" ss:Parent="rowheaderemphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderemphasisfixed__c" ss:Parent="rowheaderemphasisfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderempty" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" />');
  slXml.Add('<Interior ss:Color="#F5F7F1" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderempty__l" ss:Parent="rowheaderempty"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderempty__r" ss:Parent="rowheaderempty"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderempty__c" ss:Parent="rowheaderempty"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderfixed" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Courier New, Courier" ss:Size="10" />');
  slXml.Add('<Interior ss:Color="#F5F7F1" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderfixed__l" ss:Parent="rowheaderfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderfixed__r" ss:Parent="rowheaderfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderfixed__c" ss:Parent="rowheaderfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderstrong" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" />');
  slXml.Add('<Interior ss:Color="#F5F7F1" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderstrong__l" ss:Parent="rowheaderstrong"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderstrong__r" ss:Parent="rowheaderstrong"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderstrong__c" ss:Parent="rowheaderstrong"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderstrongfixed" ss:Parent="table">');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Courier New, Courier, monospace" ss:Size="10" ss:Bold="1" />');
  slXml.Add('<Interior ss:Color="#F5F7F1" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderstrongfixed__l" ss:Parent="rowheaderstrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderstrongfixed__r" ss:Parent="rowheaderstrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="rowheaderstrongfixed__c" ss:Parent="rowheaderstrongfixed"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter__l" ss:Parent="systemfooter"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter__r" ss:Parent="systemfooter"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter__c" ss:Parent="systemfooter"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter10" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter10__l" ss:Parent="systemfooter10"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter10__r" ss:Parent="systemfooter10"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter10__c" ss:Parent="systemfooter10"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter2" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter2__l" ss:Parent="systemfooter2"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter2__r" ss:Parent="systemfooter2"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter2__c" ss:Parent="systemfooter2"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter3" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter3__l" ss:Parent="systemfooter3"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter3__r" ss:Parent="systemfooter3"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter3__c" ss:Parent="systemfooter3"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter4" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter4__l" ss:Parent="systemfooter4"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter4__r" ss:Parent="systemfooter4"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter4__c" ss:Parent="systemfooter4"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter5" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter5__l" ss:Parent="systemfooter5"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter5__r" ss:Parent="systemfooter5"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter5__c" ss:Parent="systemfooter5"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter6" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter6__l" ss:Parent="systemfooter6"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter6__r" ss:Parent="systemfooter6"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter6__c" ss:Parent="systemfooter6"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter7" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter7__l" ss:Parent="systemfooter7"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter7__r" ss:Parent="systemfooter7"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter7__c" ss:Parent="systemfooter7"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter8" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter8__l" ss:Parent="systemfooter8"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter8__r" ss:Parent="systemfooter8"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter8__c" ss:Parent="systemfooter8"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter9" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter9__l" ss:Parent="systemfooter9"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter9__r" ss:Parent="systemfooter9"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemfooter9__c" ss:Parent="systemfooter9"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="12" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle__l" ss:Parent="systemtitle"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle__r" ss:Parent="systemtitle"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle__c" ss:Parent="systemtitle"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle10" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="12" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle10__l" ss:Parent="systemtitle10"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle10__r" ss:Parent="systemtitle10"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle10__c" ss:Parent="systemtitle10"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle2" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="12" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle2__l" ss:Parent="systemtitle2"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle2__r" ss:Parent="systemtitle2"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle2__c" ss:Parent="systemtitle2"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle3" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="12" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle3__l" ss:Parent="systemtitle3"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle3__r" ss:Parent="systemtitle3"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle3__c" ss:Parent="systemtitle3"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle4" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="12" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle4__l" ss:Parent="systemtitle4"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle4__r" ss:Parent="systemtitle4"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle4__c" ss:Parent="systemtitle4"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle5" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="12" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle5__l" ss:Parent="systemtitle5"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle5__r" ss:Parent="systemtitle5"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle5__c" ss:Parent="systemtitle5"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle6" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="12" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle6__l" ss:Parent="systemtitle6"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle6__r" ss:Parent="systemtitle6"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle6__c" ss:Parent="systemtitle6"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle7" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="12" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle7__l" ss:Parent="systemtitle7"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle7__r" ss:Parent="systemtitle7"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle7__c" ss:Parent="systemtitle7"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle8" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="12" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle8__l" ss:Parent="systemtitle8"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle8__r" ss:Parent="systemtitle8"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle8__c" ss:Parent="systemtitle8"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle9" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="12" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle9__l" ss:Parent="systemtitle9"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle9__r" ss:Parent="systemtitle9"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systemtitle9__c" ss:Parent="systemtitle9"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systitleandfootercontainer" ss:Parent="body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systitleandfootercontainer__l" ss:Parent="systitleandfootercontainer"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systitleandfootercontainer__r" ss:Parent="systitleandfootercontainer"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="systitleandfootercontainer__c" ss:Parent="systitleandfootercontainer"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="titleandnotecontainer" ss:Parent="_body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="titleandnotecontainer__l" ss:Parent="titleandnotecontainer"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="titleandnotecontainer__r" ss:Parent="titleandnotecontainer"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="titleandnotecontainer__c" ss:Parent="titleandnotecontainer"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="titlesandfooters" ss:Parent="_body">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="titlesandfooters__l" ss:Parent="titlesandfooters"><Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="titlesandfooters__r" ss:Parent="titlesandfooters"><Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="titlesandfooters__c" ss:Parent="titlesandfooters"><Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="usertext">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="warnbanner">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Bold="1" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="warncontent">');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="warncontentfixed">');
  slXml.Add('<Font ss:FontName="Courier New, Courier" ss:Size="10" ss:Color="#000000" />');
  slXml.Add('<Interior ss:Color="#D8DBD3" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="pagebreak" ss:Parent="_body">');
  slXml.Add('<Alignment/>');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Left" />');
  slXml.Add('<ss:Border ss:Position="Top" />');
  slXml.Add('<ss:Border ss:Position="Right" />');
  slXml.Add('<ss:Border ss:Position="Bottom" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datamissing_l" ss:Parent="data">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Left"/>');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" />');
  slXml.Add('<Interior ss:Color="#FFFFFF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datamissing_c" ss:Parent="data">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Center"/>');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" />');
  slXml.Add('<Interior ss:Color="#FFFFFF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="datamissing_r" ss:Parent="data">');
  slXml.Add('<Alignment ss:WrapText="1" ss:Horizontal="Right"/>');
  slXml.Add('<ss:Borders>');
  slXml.Add('<ss:Border ss:Position="Right" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('<ss:Border ss:Position="Bottom" ss:Color="#C1C1C1" ss:Weight="1" ss:LineStyle="Continuous" />');
  slXml.Add('</ss:Borders>');
  slXml.Add('<Font ss:FontName="Arial, Albany AMT, Helvetica" ss:Size="10" />');
  slXml.Add('<Interior ss:Color="#FFFFFF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__l1" ss:Parent="data__l">');
  slXml.Add('<Font ss:FontName="arial" ss:Size="8" ss:Bold="1" />');
  slXml.Add('<Interior ss:Color="#FFA8A8" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('<NumberFormat ss:Format="General" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__r1" ss:Parent="data__r">');
  slXml.Add('<Font ss:FontName="arial" ss:Size="8" ss:Bold="1" />');
  slXml.Add('<Interior ss:Color="#FFA8A8" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('<NumberFormat ss:Format="General" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__l_1" ss:Parent="data__l">');
  slXml.Add('<Font ss:FontName="arial" ss:Size="8" />');
  slXml.Add('<Interior ss:Color="#A8FFA8" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('<NumberFormat ss:Format="General" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__r_1" ss:Parent="data__r">');
  slXml.Add('<Font ss:FontName="arial" ss:Size="8" />');
  slXml.Add('<Interior ss:Color="#A8FFA8" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('<NumberFormat ss:Format="General" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__r_2" ss:Parent="datamissing_r">');
  slXml.Add('<Font ss:FontName="arial" ss:Size="8" />');
  slXml.Add('<Interior ss:Color="#A8FFA8" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('<NumberFormat ss:Format="General" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__l_2" ss:Parent="data__l">');
  slXml.Add('<Font ss:FontName="arial" ss:Size="8" />');
  slXml.Add('<Interior ss:Color="#FFFFFF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('<NumberFormat ss:Format="General" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__r_3" ss:Parent="data__r">');
  slXml.Add('<Font ss:FontName="arial" ss:Size="8" />');
  slXml.Add('<Interior ss:Color="#FFFFFF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('<NumberFormat ss:Format="General" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__r_4" ss:Parent="datamissing_r">');
  slXml.Add('<Font ss:FontName="arial" ss:Size="8" />');
  slXml.Add('<Interior ss:Color="#FFFFFF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('<NumberFormat ss:Format="General" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__l_3" ss:Parent="data__l">');
  slXml.Add('<Font ss:FontName="arial" ss:Size="8" ss:Bold="1" />');
  slXml.Add('<Interior ss:Color="#FF5757" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('<NumberFormat ss:Format="General" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__r_5" ss:Parent="data__r">');
  slXml.Add('<Font ss:FontName="arial" ss:Size="8" ss:Bold="1" />');
  slXml.Add('<Interior ss:Color="#FF5757" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('<NumberFormat ss:Format="General" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__l_4" ss:Parent="data__l">');
  slXml.Add('<Font ss:FontName="arial" ss:Size="8" ss:Bold="1" />');
  slXml.Add('<Interior ss:Color="#A8A8FF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('<NumberFormat ss:Format="General" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__r_6" ss:Parent="data__r">');
  slXml.Add('<Font ss:FontName="arial" ss:Size="8" ss:Bold="1" />');
  slXml.Add('<Interior ss:Color="#A8A8FF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('<NumberFormat ss:Format="General" />');
  slXml.Add('</Style>');
  slXml.Add('<Style ss:ID="data__r_7" ss:Parent="datamissing_r">');
  slXml.Add('<Font ss:FontName="arial" ss:Size="8" ss:Bold="1" />');
  slXml.Add('<Interior ss:Color="#A8A8FF" ss:Pattern="Solid" />');
  slXml.Add('<Protection ss:Protected="1" />');
  slXml.Add('<NumberFormat ss:Format="General" />');
  slXml.Add('</Style>');
  slXml.Add('</Styles>');
end;
end.
